@AbapCatalog.sqlViewName: 'ZEVOCPRITEM'
@AbapCatalog.compiler.compareFilter: true
@AccessControl.authorizationCheck: #CHECK
@EndUserText.label: 'Purchase Requisition Item (C2P)'
@ObjectModel.usageType: { serviceQuality: #D, sizeCategory: #XL, dataClass: #TRANSACTIONAL }
define view ZEVO_C_PurchRequisitionItem
  as select from C_PurchaseRequisitionItemDEX
  association [0..*] to ZEVO_C_PurchaseOrderItem as _PurchaseOrderItem
    on $projection.PurchaseRequisition = _PurchaseOrderItem.PurchaseRequisition and $projection.PurchaseRequisitionItem = _PurchaseOrderItem.PurchaseRequisitionItem
  association [0..*] to ZEVO_C_PurchContractItem as _PurchaseContractItem
    on $projection.PurchaseContract = _PurchaseContractItem.PurchaseContract and $projection.PurchaseContractItem = _PurchaseContractItem.PurchaseContractItem
  association [0..1] to ZEVO_C_BusinessPartner as _Supplier
    on $projection.Supplier = _Supplier.BusinessPartner
{
  key PurchaseRequisition,
  key PurchaseRequisitionItem,
      PurchaseReqnItemUniqueID,
      PurchasingDocument,
      PurchasingDocumentItem,
      PurReqnReleaseStatus,
      PurchaseRequisitionType,
      PurchasingDocumentSubtype,
      PurchasingDocumentItemCategory,
      PurchaseRequisitionItemText,
      AccountAssignmentCategory,
      Material,
      MaterialGroup,
      PurchasingDocumentCategory,
      PurchaseRequisitionPrice,
      MaterialGoodsReceiptDuration,
      ReleaseCode,
      PurchaseRequisitionReleaseDate,
      PurchasingOrganization,
      PurchasingGroup,
      Plant,
      SourceOfSupplyIsAssigned,
      SupplyingPlant,
      PurReqnLimitConsumptionAmt,
      DeliveryDate,
      CreationDate,
      ProcessingStatus,
      PurchasingInfoRecord,
      Supplier,
      IsDeleted,
      FixedSupplier,
      RequisitionerName,
      CreatedByUser,
      PurReqCreationDate,
      DeliveryAddressId,
      ManualDeliveryAddressId,
      PurReqnItemCurrency,
      MaterialPlannedDeliveryDurn,
      DelivDateCategory,
      MultipleAcctAssgmtDistribution,
      StorageLocation,
      PurReqnSSPRequestor,
      PurReqnSSPAuthor,
      PurchaseContract,
      PurReqnSourceOfSupplyType,
      PurchaseContractItem,
      ConsumptionPosting,
      PurReqnOrigin,
      PurReqnSSPCatalog,
      PurReqnSSPCatalogItem,
      PurReqnSSPCrossCatalogItem,
      IsPurReqnBlocked,
      ItemDeliveryAddressID,
      Language,
      IsClosed,
      ReleaseIsNotCompleted,
      ServicePerformer,
      ProductType,
      PurchaseRequisitionStatus,
      ReleaseStrategy,
      PerformancePeriodStartDate,
      PerformancePeriodEndDate,
      CompanyCode,
      SupplierMaterialNumber,
      Batch,
      MaterialRevisionLevel,
      MinRemainingShelfLife,
      ItemNetAmount,
      GoodsReceiptIsExpected,
      InvoiceIsExpected,
      GoodsReceiptIsNonValuated,
      RequirementTracking,
      MRPController,
      TaxCode,
      PurchaseRequisitionIsFixed,
      AddressID,
      @Semantics.systemDateTime.lastChangedAt: true
      LastChangeDateTime,
      ProcurementHubSourceSystem,
      ExtPurgOrgForPurg,
      ExtCompanyCodeForPurg,
      ExtPlantForPurg,
      ExtInfoRecordForPurg,
      ExtContractItemForPurg,
      ExtContractForPurg,
      ExtDesiredSupplierForPurg,
      ExtFixedSupplierForPurg,
      ExtMaterialForPurg,
      RequestedQuantity,
      PurReqnPriceQuantity,
      BaseUnit,
      IsPurReqnCmplt,
      PurReqnItemBlockingReasonText,
      InventorySpecialStockType,
      QuotaArrangement,
      QuotaArrangementItem,
      _PurchaseOrderItem,
      _PurchaseContractItem,
      _Supplier
}
