@AbapCatalog.sqlViewName: 'ZEVOCBPARTNER'
@AbapCatalog.compiler.compareFilter: true
@AccessControl.authorizationCheck: #CHECK
@EndUserText.label: 'Business Partner (C2P)'
@ObjectModel.usageType: { serviceQuality: #D, sizeCategory: #XL, dataClass: #MASTER }
define view ZEVO_C_BusinessPartner
  as select from I_BusinessPartner
  association [0..*] to ZEVO_C_BPSupplier as _BPSupplier
    on $projection.BusinessPartner = _BPSupplier.BusinessPartner
{
  key BusinessPartner,
      BusinessPartnerCategory,
      AuthorizationGroup,
      BusinessPartnerUUID,
      PersonNumber,
      ETag,
      BusinessPartnerName,
      BusinessPartnerFullName,
      CreatedByUser,
      CreationDate,
      CreationTime,
      LastChangedByUser,
      LastChangeDate,
      LastChangeTime,
      BusinessPartnerIsBlocked,
      IsBusinessPurposeCompleted,
      FirstName,
      LastName,
      PersonFullName,
      OrganizationBPName1,
      OrganizationBPName2,
      OrganizationBPName3,
      OrganizationBPName4,
      InternationalLocationNumber1,
      InternationalLocationNumber2,
      InternationalLocationNumber3,
      LegalForm,
      OrganizationFoundationDate,
      OrganizationLiquidationDate,
      Industry,
      IsNaturalPerson,
      IsFemale,
      IsMale,
      IsSexUnknown,
      FormOfAddress,
      AcademicTitle,
      AcademicTitle2,
      NameFormat,
      NameCountry,
      BusinessPartnerGrouping,
      BusinessPartnerType,
      MiddleName,
      AdditionalLastName,
      GroupBusinessPartnerName1,
      GroupBusinessPartnerName2,
      CorrespondenceLanguage,
      Language,
      SearchTerm1,
      SearchTerm2,
      BPLastNameSearchHelp,
      BPFirstNameSearchHelp,
      BusinessPartnerNicknameLabel,
      IndependentAddressID,
      IsActiveEntity,
      BirthDate,
      IsMarkedForArchiving,
      ContactPermission,
      BusinessPartnerIDByExtSystem,
      LegalEntityOfOrganization,
      BusinessPartnerPrintFormat,
      BusinessPartnerDataOriginType,
      BusinessPartnerIsNotReleased,
      IsNotContractuallyCapable,
      BusinessPartnerOccupation,
      BusPartMaritalStatus,
      BusPartNationality,
      NonResidentCompanyOriginCntry,
      BusinessPartnerSalutation,
      BusinessPartnerBirthName,
      BusinessPartnerSupplementName,
      BusinessPartnerBirthPlaceName,
      NaturalPersonEmployerName,
      BusinessPartnerDeathDate,
      BusinessPartnerBirthDateStatus,
      BusinessPartnerGroupType,
      LastNamePrefix,
      LastNameSecondPrefix,
      Initials,
      GenderCodeName,
      DataControllerSet,
      DataController1,
      DataController2,
      DataController3,
      DataController4,
      DataController5,
      DataController6,
      DataController7,
      DataController8,
      DataController9,
      DataController10,
      BPDataControllerIsNotRequired,
      TrdCmplncLicenseIsMilitarySctr,
      TrdCmplncLicenseIsNuclearSctr,
      _BPSupplier
}
