@AbapCatalog.sqlViewName: 'ZEVOCPUROHIST'
@AbapCatalog.compiler.compareFilter: true
@AccessControl.authorizationCheck: #CHECK
@EndUserText.label: 'Purchase Order History (C2P)'
@ObjectModel.usageType: { serviceQuality: #D, sizeCategory: #XL, dataClass: #TRANSACTIONAL }
define view ZEVO_C_PurchaseOrderHist
  as select from C_PurchaseOrderHistoryDEX
  association [0..*] to ZEVO_C_GoodsMovementDoc as _GoodsMovement
    on $projection.PurchasingHistoryDocument = _GoodsMovement.MaterialDocument and $projection.PurchasingHistoryDocumentYear = _GoodsMovement.MaterialDocumentYear and $projection.PurchaseOrder = _GoodsMovement.PurchaseOrder and $projection.PurchaseOrderItem = _GoodsMovement.PurchaseOrderItem
  association [0..1] to ZEVO_C_SupplierInvoice as _SupplierInvoice
    on $projection.PurchasingHistoryDocument = _SupplierInvoice.SupplierInvoice and $projection.PurchasingHistoryDocumentYear = _SupplierInvoice.FiscalYear
{
  key PurchaseOrder,
  key PurchaseOrderItem,
  key AccountAssignmentNumber,
  key PurchasingHistoryDocumentType,
  key PurchasingHistoryDocumentYear,
  key PurchasingHistoryDocument,
  key PurchasingHistoryDocumentItem,
      PurchasingHistoryCategory,
      GoodsMovementType,
      PostingDate,
      Currency,
      DebitCreditCode,
      IsCompletelyDelivered,
      ReferenceDocumentFiscalYear,
      ReferenceDocument,
      ReferenceDocumentItem,
      Material,
      Plant,
      RvslofGoodsReceiptIsAllowed,
      PricingDocument,
      TaxCode,
      DocumentDate,
      InventoryValuationType,
      DocumentReferenceID,
      DeliveryQuantityUnit,
      ManufacturerMaterial,
      AccountingDocumentCreationDate,
      Quantity,
      PurOrdAmountInCompanyCodeCrcy,
      PurchaseOrderAmount,
      QtyInPurchaseOrderPriceUnit,
      GRIRAcctClrgAmtInCoCodeCrcy,
      GdsRcptBlkdStkQtyInOrdQtyUnit,
      GdsRcptBlkdStkQtyInOrdPrcUnit,
      InvoiceAmtInCoCodeCrcy,
      ShipgInstrnSupplierCompliance,
      InvoiceAmountInFrgnCurrency,
      QuantityInDeliveryQtyUnit,
      GRIRAcctClrgAmtInTransacCrcy,
      QuantityInBaseUnit,
      GRIRAcctClrgAmtInOrdTrnsacCrcy,
      InvoiceAmtInPurOrdTransacCrcy,
      VltdGdsRcptBlkdStkQtyInOrdUnit,
      VltdGdsRcptBlkdQtyInOrdPrcUnit,
      IsToBeAcceptedAtOrigin,
      ExchangeRateDifferenceAmount,
      ExchangeRate,
      DeliveryDocument,
      DeliveryDocumentItem,
      OrderPriceUnit,
      PurchaseOrderQuantityUnit,
      BaseUnit,
      DocumentCurrency,
      CompanyCodeCurrency,
      ProductTypeCode,
      IsStatisticalItem,
      IsReturnsItem,
      GoodsReceiptIsExpected,
      GoodsReceiptIsNonValuated,
      IsFinallyInvoiced,
      InvoiceIsExpected,
      PurchaseContract,
      PurchaseContractItem,
      AccountAssignmentCategory,
      PurchaseRequisition,
      PurchaseRequisitionItem,
      PurchaseOrderItemCategory,
      ServicePerformer,
      ProductGroup,
      MultipleAcctAssgmtDistribution,
      PurgDocumentItemDeletionCode,
      Supplier,
      PurchasingOrganization,
      PurchasingGroup,
      CompanyCode,
      PurchasingDocumentDeletionCode,
      ReleaseIsNotCompleted,
      PurchasingCompletenessStatus,
      _GoodsMovement,
      _SupplierInvoice
}
