@AbapCatalog.sqlViewName: 'ZEVOCPURCITEM'
@AbapCatalog.compiler.compareFilter: true
@AccessControl.authorizationCheck: #CHECK
@EndUserText.label: 'Purchase Contract Item (C2P)'
@ObjectModel.usageType: { serviceQuality: #D, sizeCategory: #XL, dataClass: #TRANSACTIONAL }
define view ZEVO_C_PurchContractItem
  as select from C_PurchaseContractItemDEX
  association [0..*] to ZEVO_C_PurchContractHist as _History
    on $projection.PurchaseContract = _History.PurchaseContract and $projection.PurchaseContractItem = _History.PurchaseContractItem
  association [0..*] to ZEVO_C_PurchaseOrderItem as _PurchaseOrderItem
    on $projection.PurchaseContract = _PurchaseOrderItem.PurchaseContract and $projection.PurchaseContractItem = _PurchaseOrderItem.PurchaseContractItem
{
  key PurchaseContract,
  key PurchaseContractItem,
      DocumentCurrency,
      OrderQuantityUnit,
      TargetQuantity,
      StorageLocation,
      MaterialGroup,
      Material,
      ContractNetPriceAmount,
      NetPriceQuantity,
      PurchasingDocumentItemCategory,
      InvoiceIsExpected,
      PurchaseContractItemText,
      InvoiceIsGoodsReceiptBased,
      GoodsReceiptIsExpected,
      Plant,
      EvaldRcptSettlmtIsAllowed,
      TargetAmount,
      PurchaseContractType,
      PurchasingDocumentCategory,
      PurchasingGroup,
      PurchasingOrganization,
      ValidityStartDate,
      ValidityEndDate,
      Supplier,
      InvoicingParty,
      SupplyingSupplier,
      CreationDate,
      @Semantics.systemDateTime.lastChangedAt: true
      LastChangeDateTime,
      ExchangeRate,
      OrderPriceUnit,
      VolumeUnit,
      Customer,
      Subcontractor,
      ReferenceDeliveryAddressId,
      ManualDeliveryAddressId,
      DeliveryAddressId,
      AccountAssignmentCategory,
      MultipleAcctAssgmtDistribution,
      OrdPriceUnitToOrderUnitDnmntr,
      OrderPriceUnitToOrderUnitNmrtr,
      SupplierMaterialNumber,
      UnderdelivTolrtdLmtRatioInPct,
      PriceIsToBePrinted,
      SupplierConfirmationControlKey,
      OverdelivTolrtdLmtRatioInPct,
      UnlimitedOverdeliveryIsAllowed,
      PurgDocPriceDate,
      PurchasingInfoRecordUpdateCode,
      PurgDocReleaseOrderQuantity,
      PurgDocOrderAcknNumber,
      PurchasingPriceIsEstimated,
      IsInfoAtRegistration,
      NoDaysReminder1,
      NoDaysReminder2,
      NoDaysReminder3,
      StockType,
      TaxCode,
      RequirementTracking,
      IsOrderAcknRqd,
      ShippingInstruction,
      GoodsReceiptIsNonValuated,
      ServicePerformer,
      ProductTypeCode,
      MaterialType,
      PurchaseContractItemFormatted,
      PurchasingContractDeletionCode,
      PurchaseContractItemUniqueID,
      PurchasingCategory,
      PurgCatName,
      _History,
      _PurchaseOrderItem
}
