@AbapCatalog.sqlViewName: 'ZEVOCPUROACCT'
@AbapCatalog.compiler.compareFilter: true
@AbapCatalog.preserveKey: true
@AccessControl.authorizationCheck: #CHECK
@EndUserText.label: 'PO Account Assignment (C2P)'
@ObjectModel.usageType: { serviceQuality: #D, sizeCategory: #XL, dataClass: #TRANSACTIONAL }
define view ZEVO_C_PurOrdAcctAssgmt
  as select from C_PurOrdAccountAssignmentDEX
  association [1..1] to ZEVO_C_PurchaseOrderItem as _PurchaseOrderItem
    on $projection.PurchaseOrder = _PurchaseOrderItem.PurchaseOrder and $projection.PurchaseOrderItem = _PurchaseOrderItem.PurchaseOrderItem
{
  key PurchaseOrder,
  key PurchaseOrderItem,
  key AccountAssignmentNumber,
      CostCenter,
      MasterFixedAsset,
      ProjectNetwork,
      Quantity,
      PurchaseOrderQuantityUnit,
      MultipleAcctAssgmtDistrPercent,
      PurgDocNetAmount,
      DocumentCurrency,
      IsDeleted,
      GLAccount,
      BusinessArea,
      SalesOrder,
      SalesOrderItem,
      SalesOrderScheduleLine,
      FixedAsset,
      OrderId,
      UnloadingPointName,
      ControllingArea,
      CostObject,
      ProfitabilitySegment,
      ProfitabilitySegment_2,
      ProfitCenter,
      WBSElementInternalID,
      ProjectNetworkInternalID,
      CommitmentItem,
      FundsCenter,
      Fund,
      FunctionalArea,
      GoodsRecipientName,
      IsFinallyInvoiced,
      RealEstateObject,
      NetworkActivityInternalID,
      PartnerAccountNumber,
      JointVentureRecoveryCode,
      SettlementReferenceDate,
      OrderInternalID,
      OrderIntBillOfOperationsItem,
      TaxCode,
      TaxJurisdiction,
      NonDeductibleInputTaxAmount,
      CostCtrActivityType,
      BusinessProcess,
      GrantID,
      BudgetPeriod,
      EarmarkedFundsDocument,
      EarmarkedFundsDocumentItem,
      ServiceDocumentType,
      ServiceDocument,
      ServiceDocumentItem,
      PurchaseOrderType,
      PurchasingOrganization,
      PurchasingGroup,
      CreationDate,
      LastChangeDateTime,
      Plant,
      AccountAssignmentCategory,
      CompanyCode,
      IsReturnsItem,
      SupplyingPlant,
      PurchaseOrderItemCategory,
      Material,
      MaterialGroup,
      PurchaseOrderDate,
      StorageLocation,
      IsCompletelyDelivered,
      PurchasingInfoRecord,
      RequirementTracking,
      PurchaseOrderItemText,
      PurgDocumentItemDeletionCode,
      PurchasingDocumentDeletionCode,
      InvoiceIsExpected,
      GoodsReceiptIsExpected,
      ProductTypeCode,
      IsStatisticalItem,
      ReleaseIsNotCompleted,
      PurchasingCompletenessStatus,
      PurchaseContract,
      PurchaseContractItem,
      _PurchaseOrderItem
}
