@AbapCatalog.sqlViewName: 'ZEVOCGOODSMVT'
@AbapCatalog.compiler.compareFilter: true
@AccessControl.authorizationCheck: #CHECK
@EndUserText.label: 'Goods Movement Document (C2P)'
@ObjectModel.usageType: { serviceQuality: #D, sizeCategory: #XL, dataClass: #TRANSACTIONAL }
define view ZEVO_C_GoodsMovementDoc
  as select from I_GoodsMovementDocumentDEX
  association [0..1] to ZEVO_C_BusinessPartner as _Supplier
    on $projection.Supplier = _Supplier.BusinessPartner
{
  key MaterialDocumentKey1,
  key MaterialDocumentKey2,
  key MaterialDocumentKey3,
  key MaterialDocumentKey4,
  key MaterialDocumentKey5,
  key MaterialDocumentKey6,
      MaterialDocumentYear,
      MaterialDocument,
      MaterialDocumentItem,
      StockIdentifyingMaterial,
      Plant,
      StockIdfgStorageLocation,
      StockIdentifyingBatch,
      SpecialStockIdfgSupplier,
      SpecialStockIdfgSalesOrder,
      SpecialStockIdfgSalesOrderItem,
      SpecialStockIdfgWBSElement,
      SpecialStockIdfgCustomer,
      InventorySpecialStockType,
      InventoryStockType,
      SpecialStockIdfgStockOwner,
      ResourceID,
      CostEstimate,
      StorageLocation,
      Material,
      Batch,
      StockOwner,
      CompanyCode,
      InventorySpecialStockValnType,
      CompanyCodeCurrency,
      MaterialBaseUnit,
      EntryUnit,
      OrderQuantityUnit,
      IsReversalMovementType,
      InventoryTransactionType,
      ConsumptionPosting,
      GoodsReceiptType,
      IssuingOrReceivingPlant,
      IssuingOrReceivingStorageLoc,
      IssgOrRcvgMaterial,
      IssgOrRcvgBatch,
      IssgOrRcvgSpclStockInd,
      IssuingOrReceivingStockType,
      IssuingOrReceivingValType,
      IssgOrRcvgResourceID,
      GoodsMovementIsCancelled,
      ReversedMaterialDocument,
      ReversedMaterialDocumentItem,
      ReversedMaterialDocumentYear,
      DocumentDate,
      AccountingDocumentType,
      CreationDate,
      CreationTime,
      PostingDate,
      FiscalYearVariant,
      FiscalYear,
      FiscalYearPeriod,
      YearDay,
      YearWeek,
      YearMonth,
      YearQuarter,
      CalendarQuarter,
      CalendarMonth,
      CalendarWeek,
      CalendarDay,
      Weekday,
      SalesOrder,
      SalesOrderItem,
      SalesOrderScheduleLine,
      PurchaseOrder,
      PurchaseOrderItem,
      ProjectNetwork,
      DeliveryDocument,
      DeliveryDocumentItem,
      WBSElementInternalID,
      ManufacturingOrder,
      ManufacturingOrderItem,
      ReferenceDocument,
      GoodsIssueOrReceiptSlipNumber,
      ReferenceDocumentFiscalYear,
      InvtryMgmtRefDocumentItem,
      InvtryMgmtReferenceDocument,
      GoodsMovementType,
      InventoryValuationType,
      CreatedByUser,
      Supplier,
      Customer,
      IsMaterialDocumentHeader,
      MaterialDocumentHeaderText,
      MaterialDocumentItemText,
      IsCompletelyDelivered,
      GoodsRecipientName,
      UnloadingPointName,
      GoodsMovementRefDocType,
      GoodsMovementReasonCode,
      ShelfLifeExpirationDate,
      ManufactureDate,
      SerialNumbersAreCreatedAutomly,
      VersionForPrintingSlip,
      ManualPrintIsTriggered,
      AccountAssignmentCategory,
      CostCenter,
      ControllingArea,
      CostObject,
      GLAccount,
      FunctionalArea,
      ProfitabilitySegment,
      ProfitabilitySegment_2,
      ProfitCenter,
      MasterFixedAsset,
      FixedAsset,
      FundsCenter,
      Fund,
      CommitmentItemShortID,
      GrantID,
      Reservation,
      ReservationItem,
      ReservationIsFinallyIssued,
      DebitCreditCode,
      TotalGoodsMvtAmtInCCCrcy,
      GoodsMovementStkAmtInCCCrcy,
      GoodsMvtCnsmpnAmtInCCCrcy,
      GdsMvtExtAmtInCoCodeCrcy,
      SlsPrcAmtInclVATInCoCodeCrcy,
      EnteredSlsAmtInCoCodeCrcy,
      MatlStkChangeQtyInBaseUnit,
      MatlCnsmpnQtyInMatlBaseUnit,
      QuantityInBaseUnit,
      QuantityInEntryUnit,
      GoodsReceiptQtyInOrderUnit,
      TransactionCode,
      IsAutomaticallyCreated,
      MaterialDocumentLine,
      MaterialDocumentParentLine,
      HierarchyNodeLevel,
      _Supplier
}
